from flask import Flask, render_template, request, jsonify
import joblib
import numpy as np

app = Flask(__name__)

# Get the trained model generated by train_model.py
model = joblib.load('model.pkl')

@app.route('/')
def index():
    return render_template('index.html')

# Route for predict 
@app.route('/predict', methods=['POST'])
# predicts the clothing size based on body measurements provided in the request
def predict():
    # Using JSON to get body measurements from the JSON request data
    data = request.get_json()
    measurements = data['measurements']

    # converting data into numpy array to be 
    # readable by the data model to pass the predict function
    measurements_array = np.array([
        measurements['Height'], 
        measurements['Weight'], 
        measurements['Waist'], 
        measurements['Hip']
    ], dtype=float).reshape(1, -1)

    # since we have converted it to numpy, we can
    # call the predict function on the array to generate the size
    predictSize = model.predict(measurements_array)

    # Round off the predicted value to the nearest integer
    predictSize = int(round(predictSize[0]))

    size_map = {
        0 : 'XS',
        1 : 'S',
        2 : 'M',
        3 : 'L',
        4 : 'XL',
        5 : 'XXL',
        6 : 'XXXL',
        7 : '4XL',
        8 : '5XL'
    }

    # map predicted integer to size model
    predictedSizeLabel = size_map[predictSize]



    # Return it in a readable format using JSON
    response = jsonify({'size' : predictedSizeLabel})
    return response



if __name__ == '__main__':
    app.run(debug=True)

